services:
  nginx:
    image: nginx:latest
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - network
    container_name: ${COMPOSE_PROJECT_NAME}-proxy
    labels:
      - "com.docker.compose.project=${COMPOSE_PROJECT_NAME}"
      - "com.docker.compose.service=${COMPOSE_PROJECT_NAME}-proxy"

networks:
  network:
    name: ${COMPOSE_PROJECT_NAME}-network
    external: true
