[project]
name = "cuse-linux-api"
version = "0.1.0"
description = "cuse Linux Platform API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.9.2",
    "annotated-types==0.7.0",
    "anyio==4.7.0",
    "click==8.1.7",
    "exceptiongroup==1.2.2",
    "fastapi[standard]==0.115.6",
    "h11==0.14.0",
    "idna==3.10",
    "pillow==10.2.0",
    "pyautogui==0.9.54",
    "python-xlib==0.33",
    "pydantic==2.10.3",
    "pydantic_core==2.27.1",
    "sniffio==1.3.1",
    "starlette==0.41.3",
    "typing_extensions==4.12.2",
    "uvicorn==0.32.1",
    "psutil==5.9.0",
]
