name: Docker Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'platforms/linux/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LINUX: ${{ github.repository }}/linux

jobs:
  check-package-update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' }}
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for linux package update
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "platforms/linux/package.json"; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build-and-push-linux:
    runs-on: ubuntu-latest
    needs: [check-package-update]
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && needs.check-package-update.outputs.should_run == 'true') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LINUX }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./platforms/linux
          file: ./platforms/linux/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
