name: NPM Publish

on:
  push:
    branches:
      - main
    paths:
      - 'packages/cli/**'

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: packages/cli
        run: bun install

      - name: Build
        working-directory: packages/cli
        run: bun run build

      - name: Bump patch version
        working-directory: packages/cli
        run: bun x npm version patch

      - name: Publish to NPM
        working-directory: packages/cli
        run: bunx npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
